const fs = require('fs');
const tracker = JSON.parse(fs.readFileSync('regions-tracker.json', 'utf8'));
tracker.regions.south_africa.candidates += 18;
tracker.regions.south_africa.ideas += 4;
tracker.total_candidates += 18;
tracker.total_ideas += 4;
tracker.total_rejected += 14;
tracker.categories_recent = ["condiments-sauces", "snacks-candy", "grocery-pantry", "health-wellness", "kitchen"];
fs.writeFileSync('regions-tracker.json', JSON.stringify(tracker, null, 2));
console.log('Updated tracker');
